name: Storybook GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.STORYBOOK_SECRET_KEY }}
          publish_dir: ./docs

      # - name: Deploy
      #   uses: JamesIves/github-pages-deploy-action@3.6.2
      #   with:
      #     branch: gh-pages
      #     folder: docs # output folder from `npm run build-storybook`
