name: Storybook test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  storybook-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: npm run storybook build -o ./public --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server public --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run test:storybook"
